# Generated by Django 2.2.2 on 2021-01-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=50)),
                ('Ptag', models.TextField(max_length=20)),
                ('Pimage', models.ImageField(default='', upload_to='main/images')),
                ('Purl', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
